development:
  output_dir: tmp/
  bioscript_server: http://bioscript.epfl.ch/
  bs_server: http://bioscript.epfl.ch/
  data_url: data/
  image_url: images/
  plugin_path: /srv/bsPlugins/
  data_path: /data/epfl/bbcf/bioscript/
  input_dir: input/
  request_input_dir: request_input/
  script_dir: script/
  home: http://bioscript.epfl.ch/home 

